package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer term;
	private java.math.BigDecimal amount;

	public Application() {
	}

	public java.lang.Integer getTerm() {
		return this.term;
	}

	public void setTerm(java.lang.Integer term) {
		this.term = term;
	}

	public java.math.BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(java.math.BigDecimal amount) {
		this.amount = amount;
	}

	public Application(java.lang.Integer term, java.math.BigDecimal amount) {
		this.term = term;
		this.amount = amount;
	}

}