package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String fullName;
	private java.math.BigDecimal incomeAnnual;
	private java.lang.Integer age;

	public Customer() {
	}

	public java.lang.String getFullName() {
		return this.fullName;
	}

	public void setFullName(java.lang.String fullName) {
		this.fullName = fullName;
	}

	public java.math.BigDecimal getIncomeAnnual() {
		return this.incomeAnnual;
	}

	public void setIncomeAnnual(java.math.BigDecimal incomeAnnual) {
		this.incomeAnnual = incomeAnnual;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public Customer(java.lang.String fullName,
			java.math.BigDecimal incomeAnnual, java.lang.Integer age) {
		this.fullName = fullName;
		this.incomeAnnual = incomeAnnual;
		this.age = age;
	}

}